# Generated by Django 4.2.3 on 2024-03-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_status_process_detection_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadurlfiredetection',
            name='image_data',
        ),
        migrations.AddField(
            model_name='fire_log',
            name='image_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
