# Generated by Django 4.2.3 on 2024-03-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_uploadurlfiredetection_image_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motion_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.CharField(blank=True, max_length=300, null=True)),
                ('detection_time', models.DateTimeField(blank=True, null=True)),
                ('image_data', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadMotionUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.CharField(max_length=300)),
                ('url', models.URLField()),
            ],
        ),
    ]
