# Generated by Django 4.2.3 on 2024-04-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_motion_log_uploadmotionurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadurlandimages',
            name='image_urls',
            field=models.CharField(max_length=5000),
        ),
    ]
