# Generated by Django 4.2.3 on 2024-03-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fire_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.CharField(blank=True, max_length=255, null=True)),
                ('detection_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
