# Generated by Django 4.2.3 on 2024-03-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_fire_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadUrlFireDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.CharField(max_length=200)),
                ('url', models.URLField()),
            ],
        ),
    ]
