# Generated by Django 4.2.3 on 2024-03-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_uploadurlfiredetection'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadurlfiredetection',
            name='image_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
