# Generated by Django 4.2.3 on 2024-03-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_uploadurlfiredetection_image_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='status_process',
            name='detection_type',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
